---
- name: set up vulnwebs
  hosts: vulnwebs
  become: yes
  gather_facts: yes
  pre_tasks:
    - name: install python3 for ansible
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - python3
        - python3-simplejson
        - python3-apt
        - python3-pip
  roles:
    - role: crivetimihai.virtualization.docker
  tasks:
    - name: install docker python module
      shell: pip3 install docker
      args:
        executable: /bin/bash
      register: output
      changed_when: output.stdout != ""
    - name: run Juice Shop
      docker_container:
        name: juice-shop
        image: bkimminich/juice-shop
        state: started
        ports:
          - '3000:3000'
    - name: run WebGoat
      docker_container:
        name: webgoat
        image: webgoat/webgoat-7.1
        state: started
        tty: yes
        ports:
          - '3001:8080'
    - name: run DVWA
      docker_container:
        name: dvwa
        image: citizenstig/dvwa
        state: started
        ports:
          - '3002:80'
