# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.define "vulnwebs" do |v|
    v.vm.provider "virtualbox" do |vb|
      vb.name = "vulnwebs"
      vb.memory = 2048
    end
    v.vm.hostname = "vulnwebs.local"
    v.vm.network "private_network", ip: "10.10.10.10"
    v.vm.provision "ansible" do |ansible|
      ansible.playbook = "../playbook.yml"
    end
  end
end
